version: '3.8'

services:
  blog_backend:
    image: blog_backend
    build:
      context: .
      dockerfile: Dockerfile # Make sure you have a Dockerfile in your backend project directory
    ports:
      - "8080:8080" # Change to the port your backend service runs on
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
